In [9]:
# randomly pick the existing design, self-generated semantic matrix
import pandas as pd
import numpy as np
import pickle

### Load Real Design

In [10]:
df = pd.read_csv("simu1_data/cr_preproc_data_mturk.csv")
df

,rt,time_elapsed,subject_ID,item,lag,category,confidence,correct,correct_num,category_label,...,position,old,yes,block_type,prev_cat,prev_cat_match,prev_cat_label,prev_cat_label_match,curr_cat_length,curr_cat_label_length
0,1640.345,71781.0,120,ARM,0,Uncategorized,1.0,True,1,BodyParts,...,0,False,False,Uncategorized,NaN,NaN,NaN,False,NaN,0
1,845.750,71783.0,422,CELLO,0,Uncategorized,5.0,False,0,Instruments,...,0,False,True,Uncategorized,NaN,NaN,NaN,False,NaN,0
2,NaN,72233.0,52,HALLWAY,0,Building,NaN,False,0,Building,...,0,False,NaN,Categorized,NaN,False,NaN,False,0.0,0
3,NaN,72813.0,20,MOUNTAIN,0,Uncategorized,NaN,False,0,Landscapes,...,0,False,NaN,Uncategorized,NaN,NaN,NaN,False,NaN,0
4,NaN,73029.0,108,ROBIN,0,Uncategorized,NaN,False,0,Birds,...,0,False,NaN,Uncategorized,NaN,NaN,NaN,False,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381055,NaN,12140412.0,228,CARROT,163,Vegetables,NaN,False,0,Vegetables,...,575,True,NaN,Categorized,Landscapes,False,Landscapes,False,20.0,20
381056,NaN,12144498.0,228,GOOSE,112,Uncategorized,NaN,False,0,Birds,...,576,True,NaN,Uncategorized,Vegetables,NaN,Vegetables,False,NaN,21
381057,NaN,12148572.0,228,PEAS,68,Vegetables,NaN,False,0,Vegetables,...,577,True,NaN,Categorized,Uncategorized,False,Birds,False,21.0,21
381058,NaN,12152653.0,228,SAW,159,Tools,NaN,False,0,Tools,...,578,True,NaN,Categorized,Vegetables,False,Vegetables,False,22.0,22
381059,NaN,12156752.0,228,GIRAFFE,129,Zoo,NaN,False,0,Zoo,...,579,True,NaN,Categorized,Tools,False,Tools,False,22.0,22

In [11]:
# drop redundant columns
df = df.drop(
    [
        "rt",
        "time_elapsed",
        "correct",
        "correct_num",
        "block_type",
        "item_name",
        "prev_cat",
        "prev_cat_match",
        "prev_cat_label",
        "prev_cat_label_match",
        "curr_cat_length",
        "curr_cat_label_length",
        # "confidence",
        "category",
    ],
    axis=1,
)
df

,subject_ID,item,lag,confidence,category_label,position,old,yes
0,120,ARM,0,1.0,BodyParts,0,False,False
1,422,CELLO,0,5.0,Instruments,0,False,True
2,52,HALLWAY,0,NaN,Building,0,False,NaN
3,20,MOUNTAIN,0,NaN,Landscapes,0,False,NaN
4,108,ROBIN,0,NaN,Birds,0,False,NaN
...,...,...,...,...,...,...,...,...
381055,228,CARROT,163,NaN,Vegetables,575,True,NaN
381056,228,GOOSE,112,NaN,Birds,576,True,NaN
381057,228,PEAS,68,NaN,Vegetables,577,True,NaN
381058,228,SAW,159,NaN,Tools,578,True,NaN
381059,228,GIRAFFE,129,NaN,Zoo,579,True,NaN

In [12]:
# drop subjects with > 250 no responses
subjlist = df.subject_ID.to_numpy()
subjlist = np.unique(subjlist)
discard = []
for subj in subjlist:
    df_subj = df.loc[df.subject_ID == subj]
    no_ans = np.isnan(df_subj.yes.to_numpy().astype("float"))
    num_no_ans = np.sum(no_ans)
    if num_no_ans > 250:
        discard.append(subj)
discard.append(200)  # additional, see David
df = df.loc[df.subject_ID.isin(discard) == False].copy()
df = df.astype({"yes": "float"})

In [13]:
# how many subjects
subjlist = df.subject_ID.to_numpy()
subjlist = np.unique(subjlist)
len(subjlist)

548

In [14]:
# add itemno
items = np.unique(df.item)
item2no = {}
for i in range(len(items)):
    item2no[items[i]] = i + 1
df["itemno"] = df.apply(lambda x: item2no[x.loc["item"]], 1)
df

,subject_ID,item,lag,confidence,category_label,position,old,yes,itemno
4,108,ROBIN,0,NaN,Birds,0,False,NaN,220
6,536,WALL,0,1.0,Building,0,False,0.0,288
15,108,TURKEY,0,6.0,FarmAnimals,1,False,1.0,280
17,469,TABLET,0,5.0,Electronics,0,False,1.0,263
18,452,NOTEBOOK,0,6.0,OfficeSupplies,0,False,1.0,177
...,...,...,...,...,...,...,...,...,...
381055,228,CARROT,163,NaN,Vegetables,575,True,NaN,43
381056,228,GOOSE,112,NaN,Birds,576,True,NaN,119
381057,228,PEAS,68,NaN,Vegetables,577,True,NaN,194
381058,228,SAW,159,NaN,Tools,578,True,NaN,228
381059,228,GIRAFFE,129,NaN,Zoo,579,True,NaN,115

In [15]:
# organize
df = df.sort_values(by=["subject_ID", "position"])
df = df.reset_index(drop=True)
df = df[["subject_ID", "position", "item", "itemno", "category_label", "lag", "old", "yes", "confidence"]]
df

,subject_ID,position,item,itemno,category_label,lag,old,yes,confidence
0,0,0,CHICKEN,53,FarmAnimals,0,False,0.0,1.0
1,0,1,BLUEBERRY,26,Fruit,0,False,0.0,1.0
2,0,2,BUS,33,Vehicles,0,False,0.0,1.0
3,0,3,LEMON,151,Fruit,0,False,0.0,1.0
4,0,4,OYSTER,187,OceanAnimals,0,False,0.0,1.0
...,...,...,...,...,...,...,...,...,...
317835,656,575,COLA,60,Beverages,37,True,0.0,2.0
317836,656,576,BASEBALL,10,Toys,115,True,1.0,8.0
317837,656,577,TEA,265,Beverages,24,True,1.0,8.0
317838,656,578,RADIO,213,Electronics,41,True,0.0,2.0
317839,656,579,FINCH,99,Birds,81,True,1.0,8.0

### Design

In [16]:
sess = np.unique(df.subject_ID)
sess

array([  0,   1,   2,   3,   5,   6,   7,   8,   9,  10,  11,  12,  14,
        16,  17,  18,  19,  21,  22,  23,  27,  28,  29,  31,  32,  35,
        37,  39,  40,  41,  42,  43,  44,  46,  47,  48,  49,  50,  51,
        53,  54,  55,  57,  58,  59,  60,  61,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  76,  77,  78,  79,  80,  81,
        83,  85,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
       112, 113, 114, 115, 116, 117, 118, 119, 121, 123, 124, 125, 126,
       127, 128, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 152, 153, 155,
       156, 157, 159, 160, 161, 162, 163, 164, 165, 166, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 178, 179, 180, 181, 183, 184, 185,
       186, 187, 189, 190, 192, 193, 195, 196, 197, 198, 199, 201, 202,
       205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
       218, 219, 220, 221, 222, 223, 224, 226, 227, 228, 229, 230, 232,
       233, 234, 235, 236, 237, 239, 240, 241, 243, 244, 245, 247, 248,
       249, 250, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262,
       263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 275, 276,
       277, 278, 279, 280, 281, 282, 285, 286, 287, 288, 289, 291, 292,
       293, 295, 296, 300, 301, 302, 304, 305, 307, 308, 309, 310, 311,
       312, 313, 314, 316, 317, 318, 319, 321, 322, 323, 324, 325, 326,
       327, 328, 329, 331, 332, 333, 334, 335, 337, 338, 339, 340, 341,
       342, 343, 344, 345, 346, 347, 348, 351, 352, 354, 355, 356, 357,
       358, 359, 360, 361, 362, 363, 365, 366, 367, 368, 369, 370, 371,
       372, 374, 377, 379, 380, 381, 382, 383, 384, 385, 386, 387, 389,
       391, 392, 393, 395, 396, 397, 398, 399, 401, 403, 404, 405, 406,
       407, 408, 411, 412, 414, 415, 416, 417, 419, 420, 421, 423, 424,
       425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 436, 438, 440,
       441, 444, 445, 446, 447, 448, 450, 451, 452, 453, 454, 456, 457,
       460, 461, 462, 464, 465, 466, 467, 468, 469, 470, 471, 472, 475,
       476, 477, 478, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489,
       493, 494, 496, 497, 499, 501, 502, 503, 504, 505, 506, 507, 508,
       509, 510, 512, 513, 514, 515, 516, 517, 518, 519, 521, 523, 524,
       525, 526, 527, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538,
       539, 541, 542, 543, 545, 546, 548, 550, 551, 552, 553, 554, 555,
       556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568,
       570, 571, 572, 573, 574, 576, 577, 578, 579, 580, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 619, 620, 621, 622, 623, 624,
       625, 626, 627, 628, 629, 630, 632, 634, 635, 636, 638, 639, 640,
       641, 642, 643, 644, 645, 646, 648, 649, 650, 651, 652, 653, 654,
       655, 656])

In [17]:
df_test = pd.DataFrame()
for i in range(len(sess)):
    tmp = df.loc[df.subject_ID == sess[i], :].copy()
    tmp["session"] = i
    df_test = pd.concat([df_test, tmp])
df_test = df_test.reset_index(drop=True)
df_test["study_itemno1"] = df_test["itemno"]
df_test["study_itemno2"] = -1
df_test["test_itemno1"] = df_test["itemno"]
df_test["test_itemno2"] = -1
df_test

,subject_ID,position,item,itemno,category_label,lag,old,yes,confidence,session,study_itemno1,study_itemno2,test_itemno1,test_itemno2
0,0,0,CHICKEN,53,FarmAnimals,0,False,0.0,1.0,0,53,-1,53,-1
1,0,1,BLUEBERRY,26,Fruit,0,False,0.0,1.0,0,26,-1,26,-1
2,0,2,BUS,33,Vehicles,0,False,0.0,1.0,0,33,-1,33,-1
3,0,3,LEMON,151,Fruit,0,False,0.0,1.0,0,151,-1,151,-1
4,0,4,OYSTER,187,OceanAnimals,0,False,0.0,1.0,0,187,-1,187,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317835,656,575,COLA,60,Beverages,37,True,0.0,2.0,547,60,-1,60,-1
317836,656,576,BASEBALL,10,Toys,115,True,1.0,8.0,547,10,-1,10,-1
317837,656,577,TEA,265,Beverages,24,True,1.0,8.0,547,265,-1,265,-1
317838,656,578,RADIO,213,Electronics,41,True,0.0,2.0,547,213,-1,213,-1
317839,656,579,FINCH,99,Birds,81,True,1.0,8.0,547,99,-1,99,-1

In [18]:
# save
with open("simu1_data/simu1_design.pkl", "wb") as outp:
    pickle.dump(df_test, outp, pickle.HIGHEST_PROTOCOL)