In [1]:
# randomly pick the existing design, self-generated random semantic matrix
import numpy as np
import pandas as pd
import pickle

### Load Real Design

In [2]:
df = pd.read_table("simu2_data/RN2_Pix.dat", sep="\s+", names=["subject", "session", "list", "recog_pos", "picture", "category", "study_pos", "old_lag", "study_lag", "confidence", "rt"])
df

,subject,session,list,recog_pos,picture,category,study_pos,old_lag,study_lag,confidence,rt
0,103,1,0,1,VA084,_OLD_,6,-999,59,6,705
1,103,1,0,2,GBEN253,_OLD_,5,-1,61,6,936
2,103,1,0,3,ONTO011,_OLD_,3,-2,64,6,678
3,103,1,0,4,ISBO1,_NEW_,-99,-999,-9999,4,1461
4,103,1,0,5,PAGETT11,_OLD_,38,-999,31,5,1799
...,...,...,...,...,...,...,...,...,...,...,...
69883,99,1,5,124,CHN639,_NEW_,-99,-999,-9999,4,1460
69884,99,1,5,125,CT173,_OLD_,39,-999,150,2,1040
69885,99,1,5,126,GRTO2,_NEW_,-99,-999,-9999,2,1269
69886,99,1,5,127,GR022,_OLD_,46,-999,145,1,887
69887,99,1,5,128,VNDPGCC,_OLD_,44,-2,148,2,1154

In [3]:
# pic to itemno & old
pics = np.unique(df.picture)
pic2itemno = {}
for i in range(len(pics)):
    pic2itemno[pics[i]] = i + 1

itemnos = []
for pic in df.picture:
    itemnos.append(pic2itemno[pic])

df["itemno"] = itemnos
df["old"] = df.category == "_OLD_"
df = df.sort_values(by=["subject", "list", "recog_pos"])
df

,subject,session,list,recog_pos,picture,category,study_pos,old_lag,study_lag,confidence,rt,itemno,old
36096,37,1,0,1,CHN211,_OLD_,9,-999,56,6,1053,195,True
36097,37,1,0,2,GBEN655,_OLD_,55,46,11,2,2306,493,True
36098,37,1,0,3,ECU104,_OLD_,52,-3,15,3,1457,376,True
36099,37,1,0,4,MXACP4,_OLD_,47,-5,21,1,2333,998,True
36100,37,1,0,5,CHN118,_NEW_,-99,-999,-9999,1,1704,184,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36091,172,1,5,124,JEROCTWL,_NEW_,-99,-999,-9999,2,1076,801,False
36092,172,1,5,125,THA064,_NEW_,-99,-999,-9999,6,808,1335,False
36093,172,1,5,126,RI003,_OLD_,28,-999,162,4,999,1245,True
36094,172,1,5,127,IND117,_NEW_,-99,-999,-9999,2,1114,747,False
36095,172,1,5,128,HIO042,_NEW_,-99,-999,-9999,2,923,640,False

In [4]:
# organize
df["yes"] = (df["confidence"] >= 4).astype(int)
df["yes"] = df.apply(lambda x: np.nan if x["confidence"] == 0 or x["rt"] < 50 or x["rt"] > 3000 else x["yes"], axis=1)
df = df.drop(columns=["session", "picture", "category", "confidence", "rt"])
df = df[["subject", "list", "recog_pos", "itemno", "old", "old_lag", "study_pos", "study_lag", "yes"]]
df

,subject,list,recog_pos,itemno,old,old_lag,study_pos,study_lag,yes
36096,37,0,1,195,True,-999,9,56,1.0
36097,37,0,2,493,True,46,55,11,0.0
36098,37,0,3,376,True,-3,52,15,0.0
36099,37,0,4,998,True,-5,47,21,0.0
36100,37,0,5,184,False,-999,-99,-9999,0.0
...,...,...,...,...,...,...,...,...,...
36091,172,5,124,801,False,-999,-99,-9999,0.0
36092,172,5,125,1335,False,-999,-99,-9999,1.0
36093,172,5,126,1245,True,-999,28,162,1.0
36094,172,5,127,747,False,-999,-99,-9999,0.0
36095,172,5,128,640,False,-999,-99,-9999,0.0

### Design

In [5]:
sess = np.unique(df.subject)
sess

array([ 37,  38,  39,  41,  45,  46,  47,  49,  50,  51,  54,  56,  57,
        59,  60,  62,  63,  64,  65,  67,  68,  69,  70,  72,  73,  74,
        75,  79,  80,  81,  82,  84,  85,  86,  87,  89,  90,  92,  94,
        95,  96,  97,  98,  99, 103, 104, 105, 109, 110, 112, 113, 114,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       130, 131, 133, 134, 136, 137, 138, 140, 141, 143, 146, 147, 151,
       153, 154, 157, 158, 160, 163, 164, 165, 167, 168, 169, 171, 172])

In [6]:
df_study = pd.DataFrame()
df_test = pd.DataFrame()

for i in range(len(sess)):
    tmp = df.loc[df.subject == sess[i]].copy()
    tmp["session"] = i

    df_test = pd.concat([df_test, tmp])

    tmp_study = tmp.loc[tmp.old == True].copy()
    tmp_study = tmp_study.sort_values(by=["list", "study_pos"])
    df_study = pd.concat([df_study, tmp_study])

df_study.reset_index(drop=True, inplace=True)
df_test.reset_index(drop=True, inplace=True)

In [7]:
df_study = df_study.drop(columns=["recog_pos", "old", "old_lag", "study_lag", "yes"])
df_study

       subject  list  itemno  study_pos  session
0           37     0    1154          1        0
1           37     0    1121          2        0
2           37     0     612          3        0
3           37     0     907          4        0
4           37     0    1358          5        0
...        ...   ...     ...        ...      ...
34939      172     5    1243         60       90
34940      172     5    1077         61       90
34941      172     5    1423         62       90
34942      172     5     968         63       90
34943      172     5    1365         64       90

[34944 rows x 5 columns]

In [8]:
df_test

,subject,list,recog_pos,itemno,old,old_lag,study_pos,study_lag,yes,session
0,37,0,1,195,True,-999,9,56,1.0,0
1,37,0,2,493,True,46,55,11,0.0,0
2,37,0,3,376,True,-3,52,15,0.0,0
3,37,0,4,998,True,-5,47,21,0.0,0
4,37,0,5,184,False,-999,-99,-9999,0.0,0
...,...,...,...,...,...,...,...,...,...,...
69883,172,5,124,801,False,-999,-99,-9999,0.0,90
69884,172,5,125,1335,False,-999,-99,-9999,1.0,90
69885,172,5,126,1245,True,-999,28,162,1.0,90
69886,172,5,127,747,False,-999,-99,-9999,0.0,90
69887,172,5,128,640,False,-999,-99,-9999,0.0,90

In [9]:
with open("simu2_data/simu2_design.pkl", "wb") as outp:
    pickle.dump(df_study, outp, pickle.HIGHEST_PROTOCOL)
    pickle.dump(df_test, outp, pickle.HIGHEST_PROTOCOL)