In [1]:
import numpy as np
import pickle
import math
from scipy.stats import sem
import matplotlib.pyplot as plt
import pandas as pd
import time
import pprint
import seaborn as sns
import statsmodels.formula.api as smf
import CMR_IA as cmr

sns.set_context("paper")
pd.set_option("display.max_columns", None)

In [2]:
with open("simu2_data/simu2_design.pkl", "rb") as inp:
    df_study = pickle.load(inp)
    df_test = pickle.load(inp)

In [3]:
df_study

       subject  list  itemno1  itemno2  study_pos  session
0           37     0     1154       -1          1        0
1           37     0     1121       -1          2        0
2           37     0      612       -1          3        0
3           37     0      907       -1          4        0
4           37     0     1358       -1          5        0
...        ...   ...      ...      ...        ...      ...
34939      172     5     1243       -1         60       90
34940      172     5     1077       -1         61       90
34941      172     5     1423       -1         62       90
34942      172     5      968       -1         63       90
34943      172     5     1365       -1         64       90

[34944 rows x 6 columns]

In [4]:
df_test

,subject,list,recog_pos,itemno1,itemno2,old,old_lag,study_pos,study_lag,yes,session
0,37,0,1,195,-1,True,-999,9,56,1.0,0
1,37,0,2,493,-1,True,46,55,11,0.0,0
2,37,0,3,376,-1,True,-3,52,15,0.0,0
3,37,0,4,998,-1,True,-5,47,21,0.0,0
4,37,0,5,184,-1,False,-999,-99,-9999,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
69883,172,5,124,801,-1,False,-999,-99,-9999,0.0,90
69884,172,5,125,1335,-1,False,-999,-99,-9999,1.0,90
69885,172,5,126,1245,-1,True,-999,28,162,1.0,90
69886,172,5,127,747,-1,False,-999,-99,-9999,0.0,90
69887,172,5,128,640,-1,False,-999,-99,-9999,0.0,90

In [5]:
rng = np.random.default_rng(seed=42)
n = np.max(df_test.itemno1)
s_mat = 0.1 * rng.random((n, n))
s_mat = s_mat - np.diag(np.diag(s_mat)) + np.identity(n)
for i in range(n):
    for j in range(i + 1, n):
        s_mat[i, j] = s_mat[j, i]
s_mat

array([[1.        , 0.03476736, 0.06551139, ..., 0.05391977, 0.04848248,
        0.06778896],
       [0.03476736, 1.        , 0.02100871, ..., 0.01721134, 0.04875168,
        0.07692626],
       [0.06551139, 0.02100871, 1.        , ..., 0.01195525, 0.05010965,
        0.09304466],
       ...,
       [0.05391977, 0.01721134, 0.01195525, ..., 1.        , 0.07257732,
        0.08842044],
       [0.04848248, 0.04875168, 0.05010965, ..., 0.07257732, 1.        ,
        0.05413539],
       [0.06778896, 0.07692626, 0.09304466, ..., 0.08842044, 0.05413539,
        1.        ]])

In [6]:
np.save("simu2_data/simu2_smat.npy", s_mat)