In [ ]:
import numpy as np
import json
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import CMR_IA as cmr
from CMR_IA.fitting import _simu6b_subj_stats, _simu6b_stats

RUNCMR = False
SAVERES = False
if SAVERES and not RUNCMR:
    print("Warning: SAVERES is ignored when RUNCMR is False; existing results are loaded instead.")

## Load Stimuli and Semantic Matrix

In [18]:
# Load study and test data
df_study = pd.read_parquet("data/simu6b_study.parquet")
df_test = pd.read_parquet("data/simu6b_test.parquet")

In [19]:
# Inspect study data
df_study

       study_itemno1  study_itemno2 study_item1 study_item2  list  session
0                120            459        BELT      DIAPER     0        0
1               1315           1260      SKETCH     SEAFOOD     0        0
2                357            723   COMPANION     HOSTESS     0        0
3               1551           1202        VEAL      ROCKET     0        0
4               1081           1066       PLANE     PIGMENT     0        0
...              ...            ...         ...         ...   ...      ...
35995            976            132      OMELET  BLACKBERRY     5      499
35996            904            109         MOB      BEAVER     5      499
35997            944           1237       NERVE      SAUCER     5      499
35998           1172            782       REBEL     KLEENEX     5      499
35999           1214           1039        RUBY     PELICAN     5      499

[36000 rows x 6 columns]

In [20]:
# Inspect test data
df_test

,test_itemno1,test_itemno2,test_item,correct_ans,order,rep,test,list,session,test_pos,pair_idx
0,51,-1,ASTRONAUT,1083,2,1,1,0,0,1,8
1,1202,-1,ROCKET,1551,2,1,1,0,0,2,4
2,979,-1,OPERATOR,142,1,1,1,0,0,3,11
3,134,-1,BLADE,105,1,1,1,0,0,4,9
4,1081,-1,PLANE,1066,1,1,1,0,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
71995,1237,-1,SAUCER,944,2,1,2,5,499,20,35998
71996,782,-1,KLEENEX,1172,2,1,2,5,499,21,35999
71997,132,-1,BLACKBERRY,976,2,1,2,5,499,22,35996
71998,58,-1,ATTORNEY,663,1,1,2,5,499,23,35990
71999,109,-1,BEAVER,904,2,1,2,5,499,24,35997

In [21]:
# Load semantic matrix
sem_mat = np.load("../wordpools/ltp_FR_similarity_matrix.npy")

## Run CMR-IA

In [22]:
# Define parameters and load PSO results
params = cmr.load_params("6b", params_path="data/6b_260701_100-50.json", fixed_params={"learn_while_retrieving": True, "nitems_in_accumulator": 96})
params

{'beta_enc': 0.743944,
 'beta_rec': 0.212501,
 'beta_cue': 0.95618,
 'beta_rec_post': 0.421787,
 'beta_distract': 0.117606,
 'beta_enc_inpair': None,
 's_fc': 0.034812,
 's_cf': 0.908361,
 'phi_s': 4.390931,
 'phi_d': 3.112654,
 'psi_s': 0.0,
 'psi_c': 1.0,
 'd_assoc': None,
 'use_new_context': True,
 'use_flexible_thresh': True,
 'c_d': 0.0,
 'thresh_kernel_len': 10,
 'c_thresh_itm': 1.0,
 'c_thresh_assoc': 1.0,
 'c_s': 0.0,
 'thresh_sigma': 0.0,
 'recog_slope': 1.0,
 'kappa': 0.062971,
 'eta': 0.024418,
 'omega': 6.376088,
 'alpha': 0.786734,
 'lamb': 0.137869,
 'c_thresh': 0.023438,
 'ban_recall': None,
 'rec_time_limit': 60000.0,
 'dt': 10,
 'nitems_in_accumulator': 96,
 'max_recalls': 50,
 'learn_while_retrieving': True,
 'gamma_fc': 0.672222,
 'gamma_cf': 0.523209}

In [23]:
# Run model or load saved results
if RUNCMR:
    df_simu, f_in, f_dif = cmr.run_success_multi_sess(params, df_study, df_test, sem_mat, mode="CR-CR")
    df_simu["test_pos"] = df_test["test_pos"]
    df_simu = df_simu.merge(df_test, on=["session", "list", "test_itemno1", "test_itemno2", "test_pos"])
    df_simu["correct"] = df_simu.s_resp == df_simu.correct_ans
    if SAVERES:
        df_simu.to_parquet("data/simu6b_result.parquet")
else:
    df_simu = pd.read_parquet("data/simu6b_result.parquet")
df_simu

100%|██████████| 500/500 [00:56<00:00,  8.87it/s]

CMR Time: 56.49548864364624

,session,list,test_itemno1,test_itemno2,s_resp,s_rt,csim,thresh,test_pos,test_item,correct_ans,order,rep,test,pair_idx,correct
0,0,0,51,-1,1083,3250,0.860322,0.023438,1,ASTRONAUT,1083,2,1,1,8,True
1,0,0,1202,-1,1551,2300,0.854042,0.023438,2,ROCKET,1551,2,1,1,4,True
2,0,0,979,-1,-1,-1,-1.000000,-1.000000,3,OPERATOR,142,1,1,1,11,False
3,0,0,134,-1,105,2240,0.867731,0.023438,4,BLADE,105,1,1,1,9,True
4,0,0,1081,-1,1066,4370,0.857588,0.023438,5,PLANE,1066,1,1,1,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71995,499,5,1237,-1,944,1200,0.943558,0.023438,20,SAUCER,944,2,1,2,35998,True
71996,499,5,782,-1,-1,-1,-1.000000,-1.000000,21,KLEENEX,1172,2,1,2,35999,False
71997,499,5,132,-1,-1,-1,-1.000000,-1.000000,22,BLACKBERRY,976,2,1,2,35996,False
71998,499,5,58,-1,1294,1530,0.678882,0.023438,23,ATTORNEY,663,1,1,2,35990,False
71999,499,5,109,-1,904,4210,0.945196,0.023438,24,BEAVER,904,2,1,2,35997,True

## Analysis

In [24]:
# Get condition and congruence
df_cond = df_simu.groupby(["pair_idx", "test"])["order"].mean().to_frame(name="corr_rate").reset_index()
df_cond = df_cond.pivot_table(index="pair_idx", columns="test", values="corr_rate").reset_index()
df_cond.columns = ["pair_idx", "test1", "test2"]


def cond(x):
    test1 = x["test1"]
    test2 = x["test2"]
    if test1 == 1 and test2 == 1:
        return "F-F"
    elif test1 == 1 and test2 == 2:
        return "F-B"
    elif test1 == 2 and test2 == 1:
        return "B-F"
    elif test1 == 2 and test2 == 2:
        return "B-B"


df_cond["cond"] = df_cond.apply(lambda x: cond(x), axis=1)
df_cond["cong"] = df_cond.apply(lambda x: "Identical" if x["cond"] == "F-F" or x["cond"] == "B-B" else "Reversed", axis=1)
df_cond

       pair_idx  test1  test2 cond       cong
0             1    1.0    1.0  F-F  Identical
1             2    2.0    1.0  B-F   Reversed
2             3    1.0    1.0  F-F  Identical
3             4    2.0    1.0  B-F   Reversed
4             5    1.0    2.0  F-B   Reversed
...         ...    ...    ...  ...        ...
35995     35996    1.0    2.0  F-B   Reversed
35996     35997    1.0    2.0  F-B   Reversed
35997     35998    1.0    2.0  F-B   Reversed
35998     35999    2.0    2.0  B-B  Identical
35999     36000    2.0    1.0  B-F   Reversed

[36000 rows x 5 columns]

In [25]:
# Merge condition and congruence into df_simu
pairidx2cond = df_cond.loc[:, ["pair_idx", "cond"]].set_index("pair_idx").to_dict()["cond"]
pairidx2cong = df_cond.loc[:, ["pair_idx", "cong"]].set_index("pair_idx").to_dict()["cong"]
df_simu["cond"] = df_simu.apply(lambda x: pairidx2cond[x["pair_idx"]], axis=1)
df_simu["cong"] = df_simu.apply(lambda x: pairidx2cong[x["pair_idx"]], axis=1)
df_simu.head(24)

,session,list,test_itemno1,test_itemno2,s_resp,s_rt,csim,thresh,test_pos,test_item,correct_ans,order,rep,test,pair_idx,correct,cond,cong
0,0,0,51,-1,1083,3250,0.860322,0.023438,1,ASTRONAUT,1083,2,1,1,8,True,B-B,Identical
1,0,0,1202,-1,1551,2300,0.854042,0.023438,2,ROCKET,1551,2,1,1,4,True,B-F,Reversed
2,0,0,979,-1,-1,-1,-1.000000,-1.000000,3,OPERATOR,142,1,1,1,11,False,F-F,Identical
3,0,0,134,-1,105,2240,0.867731,0.023438,4,BLADE,105,1,1,1,9,True,F-B,Reversed
4,0,0,1081,-1,1066,4370,0.857588,0.023438,5,PLANE,1066,1,1,1,5,True,F-B,Reversed
5,0,0,357,-1,-1,-1,-1.000000,-1.000000,6,COMPANION,723,1,1,1,3,False,F-F,Identical
6,0,0,831,-1,1435,2320,0.857858,0.023438,7,LITERATURE,1435,2,1,1,7,True,B-B,Identical
7,0,0,1188,-1,641,2270,0.851133,0.023438,8,RIB,641,2,1,1,12,True,B-F,Reversed
8,0,0,1260,-1,459,1400,0.382431,0.023438,9,SEAFOOD,1315,2,1,1,2,False,B-F,Reversed
9,0,0,12,-1,-1,-1,-1.000000,-1.000000,10,AIRPLANE,226,1,1,1,10,False,F-B,Reversed
10,0,0,546,-1,1087,4770,0.859049,0.023438,11,EYELASH,1087,2,1,1,6,True,B-B,Identical
11,0,0,120,-1,459,3180,0.772944,0.023438,12,BELT,459,1,1,1,1,True,F-F,Identical
12,0,0,51,-1,1083,1670,0.939041,0.023438,13,ASTRONAUT,1083,2,1,2,8,True,B-B,Identical
13,0,0,120,-1,459,360,0.903556,0.023438,14,BELT,459,1,1,2,1,True,F-F,Identical
14,0,0,641,-1,1188,1290,0.936720,0.023438,15,GLOBE,1188,1,1,2,12,True,B-F,Reversed
15,0,0,1066,-1,1081,1070,0.941423,0.023438,16,PIGMENT,1081,2,1,2,5,True,F-B,Reversed
16,0,0,831,-1,1435,1160,0.953812,0.023438,17,LITERATURE,1435,2,1,2,7,True,B-B,Identical
17,0,0,1551,-1,1202,1160,0.949687,0.023438,18,VEAL,1202,1,1,2,4,True,B-F,Reversed
18,0,0,105,-1,134,1140,0.945227,0.023438,19,BEAN,134,2,1,2,9,True,F-B,Reversed
19,0,0,357,-1,459,4620,0.383471,0.023438,20,COMPANION,723,1,1,2,3,False,F-F,Identical
20,0,0,1315,-1,1260,1650,0.854817,0.023438,21,SKETCH,1260,1,1,2,2,True,B-F,Reversed
21,0,0,979,-1,-1,-1,-1.000000,-1.000000,22,OPERATOR,142,1,1,2,11,False,F-F,Identical
22,0,0,226,-1,-1,-1,-1.000000,-1.000000,23,CANAL,12,2,1,2,10,False,F-B,Reversed
23,0,0,546,-1,1087,1400,0.947522,0.023438,24,EYELASH,1087,2,1,2,6,True,B-B,Identical

In [26]:
# Compute _simu6b_subj_stats stats per subject
subjects = np.unique(df_simu.session)
inde_stats = []
reve_stats = []
for subj in subjects:
    df_subj_inde = df_simu.query(f"session == {subj} and cong == 'Identical'").copy()
    inde_stats.append(list(_simu6b_subj_stats(df_subj_inde)))
    df_subj_reve = df_simu.query(f"session == {subj} and cong == 'Reversed'").copy()
    reve_stats.append(list(_simu6b_subj_stats(df_subj_reve)))

In [27]:
# Inspect identical stats array
np.array(inde_stats)

array([[0.27777778, 0.02777778, 0.05555556, 0.63888889, 0.97005988],
       [0.47222222, 0.02777778, 0.08333333, 0.41666667, 0.96202532],
       [0.27777778, 0.02777778, 0.02777778, 0.66666667, 0.98265896],
       ...,
       [0.16666667, 0.        , 0.        , 0.83333333, 0.99748111],
       [0.25      , 0.05555556, 0.        , 0.69444444, 0.98973306],
       [0.44444444, 0.        , 0.02777778, 0.52777778, 0.99534884]])

In [28]:
# Inspect reversed stats array
np.array(reve_stats)

array([[0.36111111, 0.        , 0.19444444, 0.44444444, 0.96688742],
       [0.36111111, 0.08333333, 0.02777778, 0.52777778, 0.96089385],
       [0.44444444, 0.        , 0.08333333, 0.47222222, 0.98795181],
       ...,
       [0.22222222, 0.        , 0.08333333, 0.69444444, 0.98398169],
       [0.16666667, 0.02777778, 0.13888889, 0.66666667, 0.90149254],
       [0.38888889, 0.        , 0.13888889, 0.47222222, 0.9785575 ]])

In [29]:
# Print mean identical stats
np.mean(inde_stats, axis=0).round(3)

array([0.302, 0.025, 0.031, 0.643, 0.98 ])

In [30]:
# Print mean reversed stats
np.mean(reve_stats, axis=0).round(3)

array([0.309, 0.021, 0.125, 0.545, 0.941])

## Err Check

In [31]:
# Compute error against ground truth
inde_stats_mean = np.mean(inde_stats, axis=0)
reve_stats_mean = np.mean(reve_stats, axis=0)
with open("data/simu6b_gt.json") as f:
    gt = json.load(f)
inde_ground_truth = np.array(gt["inde"])
reve_ground_truth = np.array(gt["reve"])
err = np.sum(np.power(inde_stats_mean - inde_ground_truth, 2)) + np.sum(np.power(reve_stats_mean - reve_ground_truth, 2)) + np.power(inde_stats_mean[-1] - inde_ground_truth[-1], 2) + np.power(reve_stats_mean[-1] - reve_ground_truth[-1], 2)
err

0.006438519613511648

In [32]:
# Verify fitting helper
_, _, err = _simu6b_stats(df_simu, gt)
err

0.006438519613511648