In [5]:
# self-generated similar design (Schulman 1967), self-generated PEERS 984 semantic matrix
import pandas as pd
import numpy as np
import pickle

In [6]:
with open("simu4_data/simu4_word_freq.pkl", "rb") as inp:
    df = pickle.load(inp)

itemno_list = df.itemno
df.set_index("itemno", inplace=True)
df

             item  itemno_old  freq  quantile
itemno
1         ABDOMEN           1   110         2
2         ACROBAT           4    17         0
3           ADULT           8   906         8
4           ALLEY          15   165         4
5       ALLIGATOR          16    12         0
...           ...         ...   ...       ...
980          YOKE        1632    12         0
981          YOLK        1633    47         1
982         YOUTH        1634  1159         8
983        ZIPPER        1636    24         0
984           ZOO        1637   156         3

[984 rows x 4 columns]

In [7]:
rng = np.random.default_rng(seed=42)
simu_sess_num = 1000
simu_old_num = 100
simu_new_num = 100

In [8]:
df_study = pd.DataFrame()
df_test = pd.DataFrame()

for i in range(simu_sess_num):

    words = rng.choice(itemno_list, simu_old_num + simu_new_num, replace=False)
    old_words = words[0:simu_old_num]
    new_words = words[simu_old_num : simu_old_num + simu_new_num]
    test_words = rng.permutation(np.concatenate([old_words, new_words]))

    tmp_study = df.loc[old_words]
    tmp_study["session"] = i
    tmp_study["list"] = 0
    df_study = pd.concat([df_study, tmp_study], axis=0)

    tmp_test = df.loc[test_words]
    tmp_test["session"] = i
    tmp_test["list"] = 0
    tmp_test["position"] = np.arange(len(test_words))
    tmp_test["old"] = np.isin(test_words, old_words)
    df_test = pd.concat([df_test, tmp_test], axis=0)

df_study.reset_index(inplace=True)
df_test.reset_index(inplace=True)

df_study.rename(columns={"itemno": "itemno1"}, inplace=True)
df_test.rename(columns={"itemno": "itemno1"}, inplace=True)
df_study["itemno2"] = -1
df_test["itemno2"] = -1

In [9]:
df_study

       itemno1        item  itemno_old  freq  quantile  session  list  itemno2
0          316        FARM         552  1161         8        0     0       -1
1          477     LEOPARD         812   118         3        0     0       -1
2          433  INSTRUCTOR         741    78         2        0     0       -1
3           87      BOTTLE         153  1479         8        0     0       -1
4           84        BOOT         150   149         3        0     0       -1
...        ...         ...         ...   ...       ...      ...   ...      ...
99995      895        TOWN        1491  3328         9      999     0       -1
99996      633       PIANO        1057   466         6      999     0       -1
99997      843   SUBMARINE        1398   154         3      999     0       -1
99998      462   LABYRINTH         791    32         0      999     0       -1
99999      954        WAVE        1596   715         7      999     0       -1

[100000 rows x 8 columns]

In [11]:
df_test

,itemno1,item,itemno_old,freq,quantile,session,list,position,old,itemno2
0,341,FORT,595,411,6,0,0,0,True,-1
1,512,MANSION,864,156,3,0,0,1,True,-1
2,66,BENCH,121,345,6,0,0,2,True,-1
3,386,GUARD,667,658,7,0,0,3,False,-1
4,57,BEE,112,185,4,0,0,4,True,-1
...,...,...,...,...,...,...,...,...,...,...
199995,503,LUNG,850,169,4,999,0,195,True,-1
199996,891,TORNADO,1485,34,0,999,0,196,False,-1
199997,932,VEHICLE,1553,383,6,999,0,197,False,-1
199998,735,RUG,1215,321,5,999,0,198,True,-1
199999,743,SALOON,1228,181,4,999,0,199,True,-1

In [12]:
# save
with open("simu4_data/simu4_design.pkl", "wb") as outp:
    pickle.dump(df_study, outp, pickle.HIGHEST_PROTOCOL)
    pickle.dump(df_test, outp, pickle.HIGHEST_PROTOCOL)